services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: docai_api:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=Docai_api.settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on: []

volumes:
  db_data:
    driver: local
